config:
    author: Wendy Kelly
    siteName: Wendy K Kelly
    siteDescription: Wendy's personal blog 2019
    defaultPageTitle: Wendy's Thoughts
    blogTitle: Wendy's Blog
    baseUrl: https://www.wendykkelly.today

    # For Twitter cards, this logo must be a hosted url, not a relative path.
    # Must be square. Minimum size is 144x144; maximum size 4096x4096.
    websiteLogo: "https://cdn.auth0.com/blog/logos/nextjs-logo.png"

    # if your string begins with a special character, you usually have to put it in quotes
    twitterHandle: "@wendykkelly"
    twitterCardType: summary

    # This is list is used to create the links in the navigation panel
    navigation:
        - { text: Home, link: / }
        - { text: Blog, link: /blog }
        - { text: About, link: /about }

    css:
        primaryColor: "#333333" # W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
        accentColor: "linear-gradient(to right, #bc4e9c, #f80759)"
        midPink: "#bc4e9c"
        backgroundColor: "linear-gradient(to right, #ffefba, #ffffff)"  # fallback for old browsers

        black: "#333333"
