config:
    author: Wendy Kelly
    siteName: Wendy K Kelly
    siteDescription: Wendy's personal blog 2019
    defaultPageTitle: Wendy's Thoughts
    blogTitle: Wendy's Blog
    baseUrl: https://www.wendykkelly.today

    # For Twitter cards, this logo must be a hosted url, not a relative path.
    # Must be square. Minimum size is 144x144; maximum size 4096x4096.
    websiteLogo: "https://cdn.auth0.com/blog/logos/nextjs-logo.png"

    # if your string begins with a special character, you usually have to put it in quotes
    twitterHandle: "@wendykkelly"
    twitterCardType: summary

    # This is list is used to create the links in the navigation panel
    navigation:
        - { text: Home, link: / }
        - { text: Blog, link: /blog }
        - { text: About, link: /about }

    css:
        primaryColor: "#eeeeee" # W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
        accentColor: "linear-gradient(135deg, rgba(26, 188, 156, 1) 0%, rgba(142, 68, 173, 1) 100%)"
        lightGray: "333333"
        backgroundColor: "linear-gradient(to right, #414345, #232526)"  # fallback for old browsers

        black: "cccccc"

        agent1:
          - opacity: 0
          - animation: fade-in-right ease 0.4s forwards


        agent2:
          - transform: scaleX(0)
          - transform-origin: left
          - animation: grow-left cubic-bezier(0.785, 0.135, 0.15, 0.86) 0.5s forwards
          - animation-delay: 0.4s

        agent3:
          - opacity: 0
          - animation: fade-in-right ease 0.4s forwards
          - animation-delay: 0.8s
